ci: use Nix to provide Rust toolchain
Signed-off-by: NotAShelf <raf@notashelf.dev>
Change-Id: I41b52254944849be57d3f7e7947e831c6a6a6964

diff --git a/.github/workflows/rust.yaml b/.github/workflows/rust.yaml
--- a/.github/workflows/rust.yaml
+++ b/.github/workflows/rust.yaml
@@ -30,7 +30,7 @@ jobs:
         with:
           filters: |
             files:
-              - '.github/workflows/rust.yml'
+              - '.github/workflows/rust.yaml'
               - 'Cargo.toml'
               - 'Cargo.lock'
               - 'crates/**'
@@ -42,25 +42,17 @@ jobs:
     strategy:
       matrix:
         include:
-          - os: ubuntu-latest
-            target: x86_64-unknown-linux-gnu
-          - os: macos-latest
-            target: x86_64-apple-darwin
+          - os: ubuntu-24.04
+          - os: ubuntu-24.04-arm
     runs-on: ${{ matrix.os }}
     steps:
       - name: Checkout Repository
         uses: actions/checkout@v6
 
-      - name: Install Rust
-        uses: dtolnay/rust-toolchain@stable
-        with:
-          targets: ${{ matrix.target }}
-
-      - name: Cache dependencies
-        uses: Swatinem/rust-cache@v2
+      - uses: cachix/install-nix-action@v31
 
       - name: Build
-        run: cargo build --release --target ${{ matrix.target }}
+        run: nix build .#ncro -L --no-link
 
   test:
     name: Test
@@ -76,16 +68,7 @@ jobs:
         with:
           fetch-depth: 2
 
-      - name: Install Rust
-        uses: dtolnay/rust-toolchain@stable
-
-      - name: Cache Dependencies
-        uses: Swatinem/rust-cache@v2
-
-      - name: Install cargo-nextest
-        uses: taiki-e/install-action@v2.62.22
-        with:
-          tool: cargo-nextest
+      - uses: cachix/install-nix-action@v31
 
       - name: Run nextest
         id: nextest
@@ -94,7 +77,7 @@ jobs:
           export NEXTEST_EXPERIMENTAL_LIBTEST_JSON=1
 
           # Run tests and capture NDJSON output
-          cargo nextest run --message-format libtest-json-plus > test-output.ndjson || true
+          nix develop --command cargo nextest run --message-format libtest-json-plus > test-output.ndjson || true
 
           # Count passed / failed tests
           passed=$(jq -c '. | select(.type=="test" and .event=="ok")' test-output.ndjson | wc -l)
@@ -111,7 +94,10 @@ jobs:
             pct=0
           fi
 
-          echo "passed=$passed" >> $GITHUB_OUTPUT
-          echo "failed=$failed" >> $GITHUB_OUTPUT
-          echo "total=$total" >> $GITHUB_OUTPUT
-          echo "pct=$pct" >> $GITHUB_OUTPUT
+          # Can be used later for, e.g., banners
+          {
+            echo "passed=$passed"
+            echo "failed=$failed"
+            echo "total=$total"
+            echo "pct=$pct"
+          } >> "$GITHUB_OUTPUT"
